export { default as Home } from "./Home"
export { default as Inventory } from "./Inventory"
export { default as Invoice } from "./Invoice"
export { default as Catalog } from "./Catalog"
export { default as POS } from "./POS"